server:
  port: 8100

eureka:
  instance:
    hostname: eureka8100
  client:
    register-with-eureka: false  # 指定当前主机是否需要向Eureka Server注册自己
    fetch-registry: false   # 指定当前主机是否需要从Eureka Server下载服务注册表
    service-url:
      defaultZone: http://eureka8100:8100/eureka,http://eureka8200:8200/eureka,http://eureka8300:8300/eureka