# server
server:
  port: 8380
# spring
spring:
  application:
    name: abcmsc-consumer-depart
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    metadata-map:
      host-mark: gray-host