server:
  port: 8084

spring:
  # 指定当前微服务名称
  application:
    name: abcmsc-provider-depart

  # 配置spring data jpa
  jpa:
    # 指定是否在spring容器启动时创建表，默认false
    generate-ddl: true
    # 指定在控制台是否显示SQL语句，默认false
    show-sql: true
    # 指定应用重启后不重新更新表内容
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wyx_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

eureka:
  client:
    service-url:
      # 指定当前Client所要连接的eureka Server
      defaultZone: http://localhost:8000/eureka