spring:
  application:
    name: abcmsc-consumer-depart
  # redis
  redis:
    cluster:
      nodes:
        - 192.168.1.13:7001
        - 192.168.1.13:7002
        - 192.168.1.13:7003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
