server:
  port: 8081

spring:
  application:
    name: abcmsc-provider-depart # 指定当前微服务名称
  # 配置spring data jpa
  jpa:
    generate-ddl: true # 指定是否在spring容器启动时创建表，默认false
    show-sql: true # 指定在控制台是否显示SQL语句，默认false
    hibernate:
      ddl-auto: none # 指定应用重启后不重新更新表内容
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wyx_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # zipkin
  zipkin:
    base-url: http://localhost:9411/ # 指定zipkin服务器地址
  # sleuth
  sleuth:
    sampler:
      probability: 1.0 # 设置采样比例为1.0，即全部都需要，默认0.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka # 指定当前Client所要连接的eureka Server