# spring
spring:
  application:
    name: abcmsc-consumer-depart
  # zipkin
  zipkin:
    base-url: http://localhost:9411/ # 指定zipkin服务器地址
  # sleuth
  sleuth:
    sampler:
      probability: 1.0 # 设置采样比例为1.0，即全部都需要，默认0.1

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
