# server
server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:
          # 指定git远程库地址
          uri: https://github.com/justwyx/wyx-spring-cloud-config-center.git
          # 指定获取到git远程库连接的超时时限，默认为5秒
          timeout: 5
          # 指定要操作的git远程库分支，默认master
          default-label: master
          username: 1012765202@qq.com
          password: Wyx1994612.github
  # 指定要连接的kafka集群
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094

# 开启actuator的bus-refresh监控终端
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
